FROM python:3.7

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/
COPY . /usr/src/app/

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction

CMD ["python","-u","main.py"]